/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWAccountUpdateVerificationRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWAccountUpdateVerificationRequest::AWAccountUpdateVerificationRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWAccountUpdateVerificationRequest::AWAccountUpdateVerificationRequest() {
    this->initializeModel();
}

AWAccountUpdateVerificationRequest::~AWAccountUpdateVerificationRequest() {}

void AWAccountUpdateVerificationRequest::initializeModel() {

    m_user_id_isSet = false;
    m_user_id_isValid = false;

    m_secret_isSet = false;
    m_secret_isValid = false;
}

void AWAccountUpdateVerificationRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWAccountUpdateVerificationRequest::fromJsonObject(QJsonObject json) {

    m_user_id_isValid = ::OpenAPI::fromJsonValue(user_id, json[QString("userId")]);
    m_user_id_isSet = !json[QString("userId")].isNull() && m_user_id_isValid;

    m_secret_isValid = ::OpenAPI::fromJsonValue(secret, json[QString("secret")]);
    m_secret_isSet = !json[QString("secret")].isNull() && m_secret_isValid;
}

QString AWAccountUpdateVerificationRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWAccountUpdateVerificationRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_user_id_isSet) {
        obj.insert(QString("userId"), ::OpenAPI::toJsonValue(user_id));
    }
    if (m_secret_isSet) {
        obj.insert(QString("secret"), ::OpenAPI::toJsonValue(secret));
    }
    return obj;
}

QString AWAccountUpdateVerificationRequest::getUserId() const {
    return user_id;
}
void AWAccountUpdateVerificationRequest::setUserId(const QString &user_id) {
    this->user_id = user_id;
    this->m_user_id_isSet = true;
}

bool AWAccountUpdateVerificationRequest::is_user_id_Set() const{
    return m_user_id_isSet;
}

bool AWAccountUpdateVerificationRequest::is_user_id_Valid() const{
    return m_user_id_isValid;
}

QString AWAccountUpdateVerificationRequest::getSecret() const {
    return secret;
}
void AWAccountUpdateVerificationRequest::setSecret(const QString &secret) {
    this->secret = secret;
    this->m_secret_isSet = true;
}

bool AWAccountUpdateVerificationRequest::is_secret_Set() const{
    return m_secret_isSet;
}

bool AWAccountUpdateVerificationRequest::is_secret_Valid() const{
    return m_secret_isValid;
}

bool AWAccountUpdateVerificationRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_user_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_secret_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWAccountUpdateVerificationRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_user_id_isValid && m_secret_isValid && true;
}

} // namespace OpenAPI
