/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AWAccountCreatePhoneSessionRequest.h
 *
 * 
 */

#ifndef AWACCOUNTCREATEPHONESESSIONREQUEST_H
#define AWACCOUNTCREATEPHONESESSIONREQUEST_H

#include <QJsonObject>

#include <QString>

#include "src/AWEnum.h"
#include "src/AWObject.h"

#include "src/AWGlobalExport.h"

namespace OpenAPI {

class APPWRITE_EXPORT AWAccountCreatePhoneSessionRequest : public AWObject {
public:
    AWAccountCreatePhoneSessionRequest();
    AWAccountCreatePhoneSessionRequest(QString json);
    ~AWAccountCreatePhoneSessionRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getUserId() const;
    void setUserId(const QString &user_id);
    bool is_user_id_Set() const;
    bool is_user_id_Valid() const;

    QString getPhone() const;
    void setPhone(const QString &phone);
    bool is_phone_Set() const;
    bool is_phone_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString user_id;
    bool m_user_id_isSet;
    bool m_user_id_isValid;

    QString phone;
    bool m_phone_isSet;
    bool m_phone_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::AWAccountCreatePhoneSessionRequest)

#endif // AWACCOUNTCREATEPHONESESSIONREQUEST_H
