/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWAccountUpdateNameRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWAccountUpdateNameRequest::AWAccountUpdateNameRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWAccountUpdateNameRequest::AWAccountUpdateNameRequest() {
    this->initializeModel();
}

AWAccountUpdateNameRequest::~AWAccountUpdateNameRequest() {}

void AWAccountUpdateNameRequest::initializeModel() {

    m_name_isSet = false;
    m_name_isValid = false;
}

void AWAccountUpdateNameRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWAccountUpdateNameRequest::fromJsonObject(QJsonObject json) {

    m_name_isValid = ::OpenAPI::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;
}

QString AWAccountUpdateNameRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWAccountUpdateNameRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(name));
    }
    return obj;
}

QString AWAccountUpdateNameRequest::getName() const {
    return name;
}
void AWAccountUpdateNameRequest::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool AWAccountUpdateNameRequest::is_name_Set() const{
    return m_name_isSet;
}

bool AWAccountUpdateNameRequest::is_name_Valid() const{
    return m_name_isValid;
}

bool AWAccountUpdateNameRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWAccountUpdateNameRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_name_isValid && true;
}

} // namespace OpenAPI
