/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWAccountUpdateRecoveryRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWAccountUpdateRecoveryRequest::AWAccountUpdateRecoveryRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWAccountUpdateRecoveryRequest::AWAccountUpdateRecoveryRequest() {
    this->initializeModel();
}

AWAccountUpdateRecoveryRequest::~AWAccountUpdateRecoveryRequest() {}

void AWAccountUpdateRecoveryRequest::initializeModel() {

    m_user_id_isSet = false;
    m_user_id_isValid = false;

    m_secret_isSet = false;
    m_secret_isValid = false;

    m_password_isSet = false;
    m_password_isValid = false;

    m_password_again_isSet = false;
    m_password_again_isValid = false;
}

void AWAccountUpdateRecoveryRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWAccountUpdateRecoveryRequest::fromJsonObject(QJsonObject json) {

    m_user_id_isValid = ::OpenAPI::fromJsonValue(user_id, json[QString("userId")]);
    m_user_id_isSet = !json[QString("userId")].isNull() && m_user_id_isValid;

    m_secret_isValid = ::OpenAPI::fromJsonValue(secret, json[QString("secret")]);
    m_secret_isSet = !json[QString("secret")].isNull() && m_secret_isValid;

    m_password_isValid = ::OpenAPI::fromJsonValue(password, json[QString("password")]);
    m_password_isSet = !json[QString("password")].isNull() && m_password_isValid;

    m_password_again_isValid = ::OpenAPI::fromJsonValue(password_again, json[QString("passwordAgain")]);
    m_password_again_isSet = !json[QString("passwordAgain")].isNull() && m_password_again_isValid;
}

QString AWAccountUpdateRecoveryRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWAccountUpdateRecoveryRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_user_id_isSet) {
        obj.insert(QString("userId"), ::OpenAPI::toJsonValue(user_id));
    }
    if (m_secret_isSet) {
        obj.insert(QString("secret"), ::OpenAPI::toJsonValue(secret));
    }
    if (m_password_isSet) {
        obj.insert(QString("password"), ::OpenAPI::toJsonValue(password));
    }
    if (m_password_again_isSet) {
        obj.insert(QString("passwordAgain"), ::OpenAPI::toJsonValue(password_again));
    }
    return obj;
}

QString AWAccountUpdateRecoveryRequest::getUserId() const {
    return user_id;
}
void AWAccountUpdateRecoveryRequest::setUserId(const QString &user_id) {
    this->user_id = user_id;
    this->m_user_id_isSet = true;
}

bool AWAccountUpdateRecoveryRequest::is_user_id_Set() const{
    return m_user_id_isSet;
}

bool AWAccountUpdateRecoveryRequest::is_user_id_Valid() const{
    return m_user_id_isValid;
}

QString AWAccountUpdateRecoveryRequest::getSecret() const {
    return secret;
}
void AWAccountUpdateRecoveryRequest::setSecret(const QString &secret) {
    this->secret = secret;
    this->m_secret_isSet = true;
}

bool AWAccountUpdateRecoveryRequest::is_secret_Set() const{
    return m_secret_isSet;
}

bool AWAccountUpdateRecoveryRequest::is_secret_Valid() const{
    return m_secret_isValid;
}

QString AWAccountUpdateRecoveryRequest::getPassword() const {
    return password;
}
void AWAccountUpdateRecoveryRequest::setPassword(const QString &password) {
    this->password = password;
    this->m_password_isSet = true;
}

bool AWAccountUpdateRecoveryRequest::is_password_Set() const{
    return m_password_isSet;
}

bool AWAccountUpdateRecoveryRequest::is_password_Valid() const{
    return m_password_isValid;
}

QString AWAccountUpdateRecoveryRequest::getPasswordAgain() const {
    return password_again;
}
void AWAccountUpdateRecoveryRequest::setPasswordAgain(const QString &password_again) {
    this->password_again = password_again;
    this->m_password_again_isSet = true;
}

bool AWAccountUpdateRecoveryRequest::is_password_again_Set() const{
    return m_password_again_isSet;
}

bool AWAccountUpdateRecoveryRequest::is_password_again_Valid() const{
    return m_password_again_isValid;
}

bool AWAccountUpdateRecoveryRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_user_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_secret_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_password_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_password_again_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWAccountUpdateRecoveryRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_user_id_isValid && m_secret_isValid && m_password_isValid && m_password_again_isValid && true;
}

} // namespace OpenAPI
