/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWAccountCreateVerificationRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWAccountCreateVerificationRequest::AWAccountCreateVerificationRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWAccountCreateVerificationRequest::AWAccountCreateVerificationRequest() {
    this->initializeModel();
}

AWAccountCreateVerificationRequest::~AWAccountCreateVerificationRequest() {}

void AWAccountCreateVerificationRequest::initializeModel() {

    m_url_isSet = false;
    m_url_isValid = false;
}

void AWAccountCreateVerificationRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWAccountCreateVerificationRequest::fromJsonObject(QJsonObject json) {

    m_url_isValid = ::OpenAPI::fromJsonValue(url, json[QString("url")]);
    m_url_isSet = !json[QString("url")].isNull() && m_url_isValid;
}

QString AWAccountCreateVerificationRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWAccountCreateVerificationRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_url_isSet) {
        obj.insert(QString("url"), ::OpenAPI::toJsonValue(url));
    }
    return obj;
}

QString AWAccountCreateVerificationRequest::getUrl() const {
    return url;
}
void AWAccountCreateVerificationRequest::setUrl(const QString &url) {
    this->url = url;
    this->m_url_isSet = true;
}

bool AWAccountCreateVerificationRequest::is_url_Set() const{
    return m_url_isSet;
}

bool AWAccountCreateVerificationRequest::is_url_Valid() const{
    return m_url_isValid;
}

bool AWAccountCreateVerificationRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_url_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWAccountCreateVerificationRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_url_isValid && true;
}

} // namespace OpenAPI
