/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AWAlgoScrypt.h
 *
 * AlgoScrypt
 */

#ifndef AWALGOSCRYPT_H
#define AWALGOSCRYPT_H

#include <QJsonObject>

#include <QString>

#include "src/AWEnum.h"
#include "src/AWObject.h"

#include "src/AWGlobalExport.h"

namespace OpenAPI {

class APPWRITE_EXPORT AWAlgoScrypt : public AWObject {
public:
    AWAlgoScrypt();
    AWAlgoScrypt(QString json);
    ~AWAlgoScrypt() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getType() const;
    void setType(const QString &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    qint32 getCostCpu() const;
    void setCostCpu(const qint32 &cost_cpu);
    bool is_cost_cpu_Set() const;
    bool is_cost_cpu_Valid() const;

    qint32 getCostMemory() const;
    void setCostMemory(const qint32 &cost_memory);
    bool is_cost_memory_Set() const;
    bool is_cost_memory_Valid() const;

    qint32 getCostParallel() const;
    void setCostParallel(const qint32 &cost_parallel);
    bool is_cost_parallel_Set() const;
    bool is_cost_parallel_Valid() const;

    qint32 getLength() const;
    void setLength(const qint32 &length);
    bool is_length_Set() const;
    bool is_length_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString type;
    bool m_type_isSet;
    bool m_type_isValid;

    qint32 cost_cpu;
    bool m_cost_cpu_isSet;
    bool m_cost_cpu_isValid;

    qint32 cost_memory;
    bool m_cost_memory_isSet;
    bool m_cost_memory_isValid;

    qint32 cost_parallel;
    bool m_cost_parallel_isSet;
    bool m_cost_parallel_isValid;

    qint32 length;
    bool m_length_isSet;
    bool m_length_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::AWAlgoScrypt)

#endif // AWALGOSCRYPT_H
