/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AWAlgoScryptModified.h
 *
 * AlgoScryptModified
 */

#ifndef AWALGOSCRYPTMODIFIED_H
#define AWALGOSCRYPTMODIFIED_H

#include <QJsonObject>

#include <QString>

#include "src/AWEnum.h"
#include "src/AWObject.h"

#include "src/AWGlobalExport.h"

namespace OpenAPI {

class APPWRITE_EXPORT AWAlgoScryptModified : public AWObject {
public:
    AWAlgoScryptModified();
    AWAlgoScryptModified(QString json);
    ~AWAlgoScryptModified() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getType() const;
    void setType(const QString &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    QString getSalt() const;
    void setSalt(const QString &salt);
    bool is_salt_Set() const;
    bool is_salt_Valid() const;

    QString getSaltSeparator() const;
    void setSaltSeparator(const QString &salt_separator);
    bool is_salt_separator_Set() const;
    bool is_salt_separator_Valid() const;

    QString getSignerKey() const;
    void setSignerKey(const QString &signer_key);
    bool is_signer_key_Set() const;
    bool is_signer_key_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString type;
    bool m_type_isSet;
    bool m_type_isValid;

    QString salt;
    bool m_salt_isSet;
    bool m_salt_isValid;

    QString salt_separator;
    bool m_salt_separator_isSet;
    bool m_salt_separator_isValid;

    QString signer_key;
    bool m_signer_key_isSet;
    bool m_signer_key_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::AWAlgoScryptModified)

#endif // AWALGOSCRYPTMODIFIED_H
