/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWAlgoArgon2.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWAlgoArgon2::AWAlgoArgon2(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWAlgoArgon2::AWAlgoArgon2() {
    this->initializeModel();
}

AWAlgoArgon2::~AWAlgoArgon2() {}

void AWAlgoArgon2::initializeModel() {

    m_type_isSet = false;
    m_type_isValid = false;

    m_memory_cost_isSet = false;
    m_memory_cost_isValid = false;

    m_time_cost_isSet = false;
    m_time_cost_isValid = false;

    m_threads_isSet = false;
    m_threads_isValid = false;
}

void AWAlgoArgon2::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWAlgoArgon2::fromJsonObject(QJsonObject json) {

    m_type_isValid = ::OpenAPI::fromJsonValue(type, json[QString("type")]);
    m_type_isSet = !json[QString("type")].isNull() && m_type_isValid;

    m_memory_cost_isValid = ::OpenAPI::fromJsonValue(memory_cost, json[QString("memoryCost")]);
    m_memory_cost_isSet = !json[QString("memoryCost")].isNull() && m_memory_cost_isValid;

    m_time_cost_isValid = ::OpenAPI::fromJsonValue(time_cost, json[QString("timeCost")]);
    m_time_cost_isSet = !json[QString("timeCost")].isNull() && m_time_cost_isValid;

    m_threads_isValid = ::OpenAPI::fromJsonValue(threads, json[QString("threads")]);
    m_threads_isSet = !json[QString("threads")].isNull() && m_threads_isValid;
}

QString AWAlgoArgon2::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWAlgoArgon2::asJsonObject() const {
    QJsonObject obj;
    if (m_type_isSet) {
        obj.insert(QString("type"), ::OpenAPI::toJsonValue(type));
    }
    if (m_memory_cost_isSet) {
        obj.insert(QString("memoryCost"), ::OpenAPI::toJsonValue(memory_cost));
    }
    if (m_time_cost_isSet) {
        obj.insert(QString("timeCost"), ::OpenAPI::toJsonValue(time_cost));
    }
    if (m_threads_isSet) {
        obj.insert(QString("threads"), ::OpenAPI::toJsonValue(threads));
    }
    return obj;
}

QString AWAlgoArgon2::getType() const {
    return type;
}
void AWAlgoArgon2::setType(const QString &type) {
    this->type = type;
    this->m_type_isSet = true;
}

bool AWAlgoArgon2::is_type_Set() const{
    return m_type_isSet;
}

bool AWAlgoArgon2::is_type_Valid() const{
    return m_type_isValid;
}

qint32 AWAlgoArgon2::getMemoryCost() const {
    return memory_cost;
}
void AWAlgoArgon2::setMemoryCost(const qint32 &memory_cost) {
    this->memory_cost = memory_cost;
    this->m_memory_cost_isSet = true;
}

bool AWAlgoArgon2::is_memory_cost_Set() const{
    return m_memory_cost_isSet;
}

bool AWAlgoArgon2::is_memory_cost_Valid() const{
    return m_memory_cost_isValid;
}

qint32 AWAlgoArgon2::getTimeCost() const {
    return time_cost;
}
void AWAlgoArgon2::setTimeCost(const qint32 &time_cost) {
    this->time_cost = time_cost;
    this->m_time_cost_isSet = true;
}

bool AWAlgoArgon2::is_time_cost_Set() const{
    return m_time_cost_isSet;
}

bool AWAlgoArgon2::is_time_cost_Valid() const{
    return m_time_cost_isValid;
}

qint32 AWAlgoArgon2::getThreads() const {
    return threads;
}
void AWAlgoArgon2::setThreads(const qint32 &threads) {
    this->threads = threads;
    this->m_threads_isSet = true;
}

bool AWAlgoArgon2::is_threads_Set() const{
    return m_threads_isSet;
}

bool AWAlgoArgon2::is_threads_Valid() const{
    return m_threads_isValid;
}

bool AWAlgoArgon2::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_memory_cost_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_time_cost_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_threads_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWAlgoArgon2::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_type_isValid && m_memory_cost_isValid && m_time_cost_isValid && m_threads_isValid && true;
}

} // namespace OpenAPI
