/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWAlgoScrypt.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWAlgoScrypt::AWAlgoScrypt(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWAlgoScrypt::AWAlgoScrypt() {
    this->initializeModel();
}

AWAlgoScrypt::~AWAlgoScrypt() {}

void AWAlgoScrypt::initializeModel() {

    m_type_isSet = false;
    m_type_isValid = false;

    m_cost_cpu_isSet = false;
    m_cost_cpu_isValid = false;

    m_cost_memory_isSet = false;
    m_cost_memory_isValid = false;

    m_cost_parallel_isSet = false;
    m_cost_parallel_isValid = false;

    m_length_isSet = false;
    m_length_isValid = false;
}

void AWAlgoScrypt::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWAlgoScrypt::fromJsonObject(QJsonObject json) {

    m_type_isValid = ::OpenAPI::fromJsonValue(type, json[QString("type")]);
    m_type_isSet = !json[QString("type")].isNull() && m_type_isValid;

    m_cost_cpu_isValid = ::OpenAPI::fromJsonValue(cost_cpu, json[QString("costCpu")]);
    m_cost_cpu_isSet = !json[QString("costCpu")].isNull() && m_cost_cpu_isValid;

    m_cost_memory_isValid = ::OpenAPI::fromJsonValue(cost_memory, json[QString("costMemory")]);
    m_cost_memory_isSet = !json[QString("costMemory")].isNull() && m_cost_memory_isValid;

    m_cost_parallel_isValid = ::OpenAPI::fromJsonValue(cost_parallel, json[QString("costParallel")]);
    m_cost_parallel_isSet = !json[QString("costParallel")].isNull() && m_cost_parallel_isValid;

    m_length_isValid = ::OpenAPI::fromJsonValue(length, json[QString("length")]);
    m_length_isSet = !json[QString("length")].isNull() && m_length_isValid;
}

QString AWAlgoScrypt::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWAlgoScrypt::asJsonObject() const {
    QJsonObject obj;
    if (m_type_isSet) {
        obj.insert(QString("type"), ::OpenAPI::toJsonValue(type));
    }
    if (m_cost_cpu_isSet) {
        obj.insert(QString("costCpu"), ::OpenAPI::toJsonValue(cost_cpu));
    }
    if (m_cost_memory_isSet) {
        obj.insert(QString("costMemory"), ::OpenAPI::toJsonValue(cost_memory));
    }
    if (m_cost_parallel_isSet) {
        obj.insert(QString("costParallel"), ::OpenAPI::toJsonValue(cost_parallel));
    }
    if (m_length_isSet) {
        obj.insert(QString("length"), ::OpenAPI::toJsonValue(length));
    }
    return obj;
}

QString AWAlgoScrypt::getType() const {
    return type;
}
void AWAlgoScrypt::setType(const QString &type) {
    this->type = type;
    this->m_type_isSet = true;
}

bool AWAlgoScrypt::is_type_Set() const{
    return m_type_isSet;
}

bool AWAlgoScrypt::is_type_Valid() const{
    return m_type_isValid;
}

qint32 AWAlgoScrypt::getCostCpu() const {
    return cost_cpu;
}
void AWAlgoScrypt::setCostCpu(const qint32 &cost_cpu) {
    this->cost_cpu = cost_cpu;
    this->m_cost_cpu_isSet = true;
}

bool AWAlgoScrypt::is_cost_cpu_Set() const{
    return m_cost_cpu_isSet;
}

bool AWAlgoScrypt::is_cost_cpu_Valid() const{
    return m_cost_cpu_isValid;
}

qint32 AWAlgoScrypt::getCostMemory() const {
    return cost_memory;
}
void AWAlgoScrypt::setCostMemory(const qint32 &cost_memory) {
    this->cost_memory = cost_memory;
    this->m_cost_memory_isSet = true;
}

bool AWAlgoScrypt::is_cost_memory_Set() const{
    return m_cost_memory_isSet;
}

bool AWAlgoScrypt::is_cost_memory_Valid() const{
    return m_cost_memory_isValid;
}

qint32 AWAlgoScrypt::getCostParallel() const {
    return cost_parallel;
}
void AWAlgoScrypt::setCostParallel(const qint32 &cost_parallel) {
    this->cost_parallel = cost_parallel;
    this->m_cost_parallel_isSet = true;
}

bool AWAlgoScrypt::is_cost_parallel_Set() const{
    return m_cost_parallel_isSet;
}

bool AWAlgoScrypt::is_cost_parallel_Valid() const{
    return m_cost_parallel_isValid;
}

qint32 AWAlgoScrypt::getLength() const {
    return length;
}
void AWAlgoScrypt::setLength(const qint32 &length) {
    this->length = length;
    this->m_length_isSet = true;
}

bool AWAlgoScrypt::is_length_Set() const{
    return m_length_isSet;
}

bool AWAlgoScrypt::is_length_Valid() const{
    return m_length_isValid;
}

bool AWAlgoScrypt::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_cost_cpu_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_cost_memory_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_cost_parallel_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_length_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWAlgoScrypt::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_type_isValid && m_cost_cpu_isValid && m_cost_memory_isValid && m_cost_parallel_isValid && m_length_isValid && true;
}

} // namespace OpenAPI
