/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWContinentList.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWContinentList::AWContinentList(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWContinentList::AWContinentList() {
    this->initializeModel();
}

AWContinentList::~AWContinentList() {}

void AWContinentList::initializeModel() {

    m_total_isSet = false;
    m_total_isValid = false;

    m_continents_isSet = false;
    m_continents_isValid = false;
}

void AWContinentList::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWContinentList::fromJsonObject(QJsonObject json) {

    m_total_isValid = ::OpenAPI::fromJsonValue(total, json[QString("total")]);
    m_total_isSet = !json[QString("total")].isNull() && m_total_isValid;

    m_continents_isValid = ::OpenAPI::fromJsonValue(continents, json[QString("continents")]);
    m_continents_isSet = !json[QString("continents")].isNull() && m_continents_isValid;
}

QString AWContinentList::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWContinentList::asJsonObject() const {
    QJsonObject obj;
    if (m_total_isSet) {
        obj.insert(QString("total"), ::OpenAPI::toJsonValue(total));
    }
    if (continents.size() > 0) {
        obj.insert(QString("continents"), ::OpenAPI::toJsonValue(continents));
    }
    return obj;
}

qint32 AWContinentList::getTotal() const {
    return total;
}
void AWContinentList::setTotal(const qint32 &total) {
    this->total = total;
    this->m_total_isSet = true;
}

bool AWContinentList::is_total_Set() const{
    return m_total_isSet;
}

bool AWContinentList::is_total_Valid() const{
    return m_total_isValid;
}

QList<AWContinent> AWContinentList::getContinents() const {
    return continents;
}
void AWContinentList::setContinents(const QList<AWContinent> &continents) {
    this->continents = continents;
    this->m_continents_isSet = true;
}

bool AWContinentList::is_continents_Set() const{
    return m_continents_isSet;
}

bool AWContinentList::is_continents_Valid() const{
    return m_continents_isValid;
}

bool AWContinentList::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_total_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (continents.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWContinentList::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_total_isValid && m_continents_isValid && true;
}

} // namespace OpenAPI
