/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWCountryList.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWCountryList::AWCountryList(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWCountryList::AWCountryList() {
    this->initializeModel();
}

AWCountryList::~AWCountryList() {}

void AWCountryList::initializeModel() {

    m_total_isSet = false;
    m_total_isValid = false;

    m_countries_isSet = false;
    m_countries_isValid = false;
}

void AWCountryList::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWCountryList::fromJsonObject(QJsonObject json) {

    m_total_isValid = ::OpenAPI::fromJsonValue(total, json[QString("total")]);
    m_total_isSet = !json[QString("total")].isNull() && m_total_isValid;

    m_countries_isValid = ::OpenAPI::fromJsonValue(countries, json[QString("countries")]);
    m_countries_isSet = !json[QString("countries")].isNull() && m_countries_isValid;
}

QString AWCountryList::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWCountryList::asJsonObject() const {
    QJsonObject obj;
    if (m_total_isSet) {
        obj.insert(QString("total"), ::OpenAPI::toJsonValue(total));
    }
    if (countries.size() > 0) {
        obj.insert(QString("countries"), ::OpenAPI::toJsonValue(countries));
    }
    return obj;
}

qint32 AWCountryList::getTotal() const {
    return total;
}
void AWCountryList::setTotal(const qint32 &total) {
    this->total = total;
    this->m_total_isSet = true;
}

bool AWCountryList::is_total_Set() const{
    return m_total_isSet;
}

bool AWCountryList::is_total_Valid() const{
    return m_total_isValid;
}

QList<AWCountry> AWCountryList::getCountries() const {
    return countries;
}
void AWCountryList::setCountries(const QList<AWCountry> &countries) {
    this->countries = countries;
    this->m_countries_isSet = true;
}

bool AWCountryList::is_countries_Set() const{
    return m_countries_isSet;
}

bool AWCountryList::is_countries_Valid() const{
    return m_countries_isValid;
}

bool AWCountryList::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_total_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (countries.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWCountryList::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_total_isValid && m_countries_isValid && true;
}

} // namespace OpenAPI
