/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWDatabasesUpdateDocumentRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWDatabasesUpdateDocumentRequest::AWDatabasesUpdateDocumentRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWDatabasesUpdateDocumentRequest::AWDatabasesUpdateDocumentRequest() {
    this->initializeModel();
}

AWDatabasesUpdateDocumentRequest::~AWDatabasesUpdateDocumentRequest() {}

void AWDatabasesUpdateDocumentRequest::initializeModel() {

    m_data_isSet = false;
    m_data_isValid = false;

    m_permissions_isSet = false;
    m_permissions_isValid = false;
}

void AWDatabasesUpdateDocumentRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWDatabasesUpdateDocumentRequest::fromJsonObject(QJsonObject json) {

    m_data_isValid = ::OpenAPI::fromJsonValue(data, json[QString("data")]);
    m_data_isSet = !json[QString("data")].isNull() && m_data_isValid;

    m_permissions_isValid = ::OpenAPI::fromJsonValue(permissions, json[QString("permissions")]);
    m_permissions_isSet = !json[QString("permissions")].isNull() && m_permissions_isValid;
}

QString AWDatabasesUpdateDocumentRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWDatabasesUpdateDocumentRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_data_isSet) {
        obj.insert(QString("data"), ::OpenAPI::toJsonValue(data));
    }
    if (permissions.size() > 0) {
        obj.insert(QString("permissions"), ::OpenAPI::toJsonValue(permissions));
    }
    return obj;
}

AWObject AWDatabasesUpdateDocumentRequest::getData() const {
    return data;
}
void AWDatabasesUpdateDocumentRequest::setData(const AWObject &data) {
    this->data = data;
    this->m_data_isSet = true;
}

bool AWDatabasesUpdateDocumentRequest::is_data_Set() const{
    return m_data_isSet;
}

bool AWDatabasesUpdateDocumentRequest::is_data_Valid() const{
    return m_data_isValid;
}

QList<QString> AWDatabasesUpdateDocumentRequest::getPermissions() const {
    return permissions;
}
void AWDatabasesUpdateDocumentRequest::setPermissions(const QList<QString> &permissions) {
    this->permissions = permissions;
    this->m_permissions_isSet = true;
}

bool AWDatabasesUpdateDocumentRequest::is_permissions_Set() const{
    return m_permissions_isSet;
}

bool AWDatabasesUpdateDocumentRequest::is_permissions_Valid() const{
    return m_permissions_isValid;
}

bool AWDatabasesUpdateDocumentRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_data_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (permissions.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWDatabasesUpdateDocumentRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
