/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AWDocument.h
 *
 * Document
 */

#ifndef AWDOCUMENT_H
#define AWDOCUMENT_H

#include <QJsonObject>

#include <QJsonValue>
#include <QList>
#include <QMap>
#include <QString>

#include "src/AWObject.h"

#include "src/AWGlobalExport.h"

namespace OpenAPI {

class APPWRITE_EXPORT AWDocument : public AWObject, public QObject {
public:
    AWDocument();
    AWDocument(QString json);
    ~AWDocument() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getCollectionId() const;
    void setCollectionId(const QString &collection_id);
    bool is_collection_id_Set() const;
    bool is_collection_id_Valid() const;

    QString getDatabaseId() const;
    void setDatabaseId(const QString &database_id);
    bool is_database_id_Set() const;
    bool is_database_id_Valid() const;

    QString getCreatedAt() const;
    void setCreatedAt(const QString &created_at);
    bool is_created_at_Set() const;
    bool is_created_at_Valid() const;

    QString getUpdatedAt() const;
    void setUpdatedAt(const QString &updated_at);
    bool is_updated_at_Set() const;
    bool is_updated_at_Valid() const;

    QList<QString> getPermissions() const;
    void setPermissions(const QList<QString> &permissions);
    bool is_permissions_Set() const;
    bool is_permissions_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString collection_id;
    bool m_collection_id_isSet;
    bool m_collection_id_isValid;

    QString database_id;
    bool m_database_id_isSet;
    bool m_database_id_isValid;

    QString created_at;
    bool m_created_at_isSet;
    bool m_created_at_isValid;

    QString updated_at;
    bool m_updated_at_isSet;
    bool m_updated_at_isValid;

    QList<QString> permissions;
    bool m_permissions_isSet;
    bool m_permissions_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::AWDocument)

#endif // AWDOCUMENT_H
