/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AWFileEx.h
 *
 * File
 */

#ifndef AWFILEEX_H
#define AWFILEEX_H

#include <QJsonObject>

#include <QList>
#include <QString>

#include "src/AWEnum.h"
#include "src/AWObject.h"

#include "src/AWGlobalExport.h"

namespace OpenAPI {

class APPWRITE_EXPORT AWFileEx : public AWObject {
public:
    AWFileEx();
    AWFileEx(QString json);
    ~AWFileEx() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getBucketId() const;
    void setBucketId(const QString &bucket_id);
    bool is_bucket_id_Set() const;
    bool is_bucket_id_Valid() const;

    QString getCreatedAt() const;
    void setCreatedAt(const QString &created_at);
    bool is_created_at_Set() const;
    bool is_created_at_Valid() const;

    QString getUpdatedAt() const;
    void setUpdatedAt(const QString &updated_at);
    bool is_updated_at_Set() const;
    bool is_updated_at_Valid() const;

    QList<QString> getPermissions() const;
    void setPermissions(const QList<QString> &permissions);
    bool is_permissions_Set() const;
    bool is_permissions_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getSignature() const;
    void setSignature(const QString &signature);
    bool is_signature_Set() const;
    bool is_signature_Valid() const;

    QString getMimeType() const;
    void setMimeType(const QString &mime_type);
    bool is_mime_type_Set() const;
    bool is_mime_type_Valid() const;

    qint32 getSizeOriginal() const;
    void setSizeOriginal(const qint32 &size_original);
    bool is_size_original_Set() const;
    bool is_size_original_Valid() const;

    qint32 getChunksTotal() const;
    void setChunksTotal(const qint32 &chunks_total);
    bool is_chunks_total_Set() const;
    bool is_chunks_total_Valid() const;

    qint32 getChunksUploaded() const;
    void setChunksUploaded(const qint32 &chunks_uploaded);
    bool is_chunks_uploaded_Set() const;
    bool is_chunks_uploaded_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString bucket_id;
    bool m_bucket_id_isSet;
    bool m_bucket_id_isValid;

    QString created_at;
    bool m_created_at_isSet;
    bool m_created_at_isValid;

    QString updated_at;
    bool m_updated_at_isSet;
    bool m_updated_at_isValid;

    QList<QString> permissions;
    bool m_permissions_isSet;
    bool m_permissions_isValid;

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString signature;
    bool m_signature_isSet;
    bool m_signature_isValid;

    QString mime_type;
    bool m_mime_type_isSet;
    bool m_mime_type_isValid;

    qint32 size_original;
    bool m_size_original_isSet;
    bool m_size_original_isValid;

    qint32 chunks_total;
    bool m_chunks_total_isSet;
    bool m_chunks_total_isValid;

    qint32 chunks_uploaded;
    bool m_chunks_uploaded_isSet;
    bool m_chunks_uploaded_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::AWFileEx)

#endif // AWFILEEX_H
