/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AWFunctionsCreateExecutionRequest.h
 *
 * 
 */

#ifndef AWFUNCTIONSCREATEEXECUTIONREQUEST_H
#define AWFUNCTIONSCREATEEXECUTIONREQUEST_H

#include <QJsonObject>

#include <QString>

#include "src/AWEnum.h"
#include "src/AWObject.h"

#include "src/AWGlobalExport.h"

namespace OpenAPI {

class APPWRITE_EXPORT AWFunctionsCreateExecutionRequest : public AWObject {
public:
    AWFunctionsCreateExecutionRequest();
    AWFunctionsCreateExecutionRequest(QString json);
    ~AWFunctionsCreateExecutionRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getData() const;
    void setData(const QString &data);
    bool is_data_Set() const;
    bool is_data_Valid() const;

    bool isAsync() const;
    void setAsync(const bool &async);
    bool is_async_Set() const;
    bool is_async_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString data;
    bool m_data_isSet;
    bool m_data_isValid;

    bool async;
    bool m_async_isSet;
    bool m_async_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::AWFunctionsCreateExecutionRequest)

#endif // AWFUNCTIONSCREATEEXECUTIONREQUEST_H
