/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWJwt.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWJwt::AWJwt(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWJwt::AWJwt() {
    this->initializeModel();
}

AWJwt::~AWJwt() {}

void AWJwt::initializeModel() {

    m_jwt_isSet = false;
    m_jwt_isValid = false;
}

void AWJwt::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWJwt::fromJsonObject(QJsonObject json) {

    m_jwt_isValid = ::OpenAPI::fromJsonValue(jwt, json[QString("jwt")]);
    m_jwt_isSet = !json[QString("jwt")].isNull() && m_jwt_isValid;
}

QString AWJwt::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWJwt::asJsonObject() const {
    QJsonObject obj;
    if (m_jwt_isSet) {
        obj.insert(QString("jwt"), ::OpenAPI::toJsonValue(jwt));
    }
    return obj;
}

QString AWJwt::getJwt() const {
    return jwt;
}
void AWJwt::setJwt(const QString &jwt) {
    this->jwt = jwt;
    this->m_jwt_isSet = true;
}

bool AWJwt::is_jwt_Set() const{
    return m_jwt_isSet;
}

bool AWJwt::is_jwt_Valid() const{
    return m_jwt_isValid;
}

bool AWJwt::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_jwt_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWJwt::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_jwt_isValid && true;
}

} // namespace OpenAPI
