/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWLanguage.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWLanguage::AWLanguage(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWLanguage::AWLanguage() {
    this->initializeModel();
}

AWLanguage::~AWLanguage() {}

void AWLanguage::initializeModel() {

    m_name_isSet = false;
    m_name_isValid = false;

    m_code_isSet = false;
    m_code_isValid = false;

    m_native_name_isSet = false;
    m_native_name_isValid = false;
}

void AWLanguage::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWLanguage::fromJsonObject(QJsonObject json) {

    m_name_isValid = ::OpenAPI::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_code_isValid = ::OpenAPI::fromJsonValue(code, json[QString("code")]);
    m_code_isSet = !json[QString("code")].isNull() && m_code_isValid;

    m_native_name_isValid = ::OpenAPI::fromJsonValue(native_name, json[QString("nativeName")]);
    m_native_name_isSet = !json[QString("nativeName")].isNull() && m_native_name_isValid;
}

QString AWLanguage::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWLanguage::asJsonObject() const {
    QJsonObject obj;
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(name));
    }
    if (m_code_isSet) {
        obj.insert(QString("code"), ::OpenAPI::toJsonValue(code));
    }
    if (m_native_name_isSet) {
        obj.insert(QString("nativeName"), ::OpenAPI::toJsonValue(native_name));
    }
    return obj;
}

QString AWLanguage::getName() const {
    return name;
}
void AWLanguage::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool AWLanguage::is_name_Set() const{
    return m_name_isSet;
}

bool AWLanguage::is_name_Valid() const{
    return m_name_isValid;
}

QString AWLanguage::getCode() const {
    return code;
}
void AWLanguage::setCode(const QString &code) {
    this->code = code;
    this->m_code_isSet = true;
}

bool AWLanguage::is_code_Set() const{
    return m_code_isSet;
}

bool AWLanguage::is_code_Valid() const{
    return m_code_isValid;
}

QString AWLanguage::getNativeName() const {
    return native_name;
}
void AWLanguage::setNativeName(const QString &native_name) {
    this->native_name = native_name;
    this->m_native_name_isSet = true;
}

bool AWLanguage::is_native_name_Set() const{
    return m_native_name_isSet;
}

bool AWLanguage::is_native_name_Valid() const{
    return m_native_name_isValid;
}

bool AWLanguage::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_native_name_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWLanguage::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_name_isValid && m_code_isValid && m_native_name_isValid && true;
}

} // namespace OpenAPI
