/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWLog.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWLog::AWLog(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWLog::AWLog() {
    this->initializeModel();
}

AWLog::~AWLog() {}

void AWLog::initializeModel() {

    m_event_isSet = false;
    m_event_isValid = false;

    m_user_id_isSet = false;
    m_user_id_isValid = false;

    m_user_email_isSet = false;
    m_user_email_isValid = false;

    m_user_name_isSet = false;
    m_user_name_isValid = false;

    m_mode_isSet = false;
    m_mode_isValid = false;

    m_ip_isSet = false;
    m_ip_isValid = false;

    m_time_isSet = false;
    m_time_isValid = false;

    m_os_code_isSet = false;
    m_os_code_isValid = false;

    m_os_name_isSet = false;
    m_os_name_isValid = false;

    m_os_version_isSet = false;
    m_os_version_isValid = false;

    m_client_type_isSet = false;
    m_client_type_isValid = false;

    m_client_code_isSet = false;
    m_client_code_isValid = false;

    m_client_name_isSet = false;
    m_client_name_isValid = false;

    m_client_version_isSet = false;
    m_client_version_isValid = false;

    m_client_engine_isSet = false;
    m_client_engine_isValid = false;

    m_client_engine_version_isSet = false;
    m_client_engine_version_isValid = false;

    m_device_name_isSet = false;
    m_device_name_isValid = false;

    m_device_brand_isSet = false;
    m_device_brand_isValid = false;

    m_device_model_isSet = false;
    m_device_model_isValid = false;

    m_country_code_isSet = false;
    m_country_code_isValid = false;

    m_country_name_isSet = false;
    m_country_name_isValid = false;
}

void AWLog::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWLog::fromJsonObject(QJsonObject json) {

    m_event_isValid = ::OpenAPI::fromJsonValue(event, json[QString("event")]);
    m_event_isSet = !json[QString("event")].isNull() && m_event_isValid;

    m_user_id_isValid = ::OpenAPI::fromJsonValue(user_id, json[QString("userId")]);
    m_user_id_isSet = !json[QString("userId")].isNull() && m_user_id_isValid;

    m_user_email_isValid = ::OpenAPI::fromJsonValue(user_email, json[QString("userEmail")]);
    m_user_email_isSet = !json[QString("userEmail")].isNull() && m_user_email_isValid;

    m_user_name_isValid = ::OpenAPI::fromJsonValue(user_name, json[QString("userName")]);
    m_user_name_isSet = !json[QString("userName")].isNull() && m_user_name_isValid;

    m_mode_isValid = ::OpenAPI::fromJsonValue(mode, json[QString("mode")]);
    m_mode_isSet = !json[QString("mode")].isNull() && m_mode_isValid;

    m_ip_isValid = ::OpenAPI::fromJsonValue(ip, json[QString("ip")]);
    m_ip_isSet = !json[QString("ip")].isNull() && m_ip_isValid;

    m_time_isValid = ::OpenAPI::fromJsonValue(time, json[QString("time")]);
    m_time_isSet = !json[QString("time")].isNull() && m_time_isValid;

    m_os_code_isValid = ::OpenAPI::fromJsonValue(os_code, json[QString("osCode")]);
    m_os_code_isSet = !json[QString("osCode")].isNull() && m_os_code_isValid;

    m_os_name_isValid = ::OpenAPI::fromJsonValue(os_name, json[QString("osName")]);
    m_os_name_isSet = !json[QString("osName")].isNull() && m_os_name_isValid;

    m_os_version_isValid = ::OpenAPI::fromJsonValue(os_version, json[QString("osVersion")]);
    m_os_version_isSet = !json[QString("osVersion")].isNull() && m_os_version_isValid;

    m_client_type_isValid = ::OpenAPI::fromJsonValue(client_type, json[QString("clientType")]);
    m_client_type_isSet = !json[QString("clientType")].isNull() && m_client_type_isValid;

    m_client_code_isValid = ::OpenAPI::fromJsonValue(client_code, json[QString("clientCode")]);
    m_client_code_isSet = !json[QString("clientCode")].isNull() && m_client_code_isValid;

    m_client_name_isValid = ::OpenAPI::fromJsonValue(client_name, json[QString("clientName")]);
    m_client_name_isSet = !json[QString("clientName")].isNull() && m_client_name_isValid;

    m_client_version_isValid = ::OpenAPI::fromJsonValue(client_version, json[QString("clientVersion")]);
    m_client_version_isSet = !json[QString("clientVersion")].isNull() && m_client_version_isValid;

    m_client_engine_isValid = ::OpenAPI::fromJsonValue(client_engine, json[QString("clientEngine")]);
    m_client_engine_isSet = !json[QString("clientEngine")].isNull() && m_client_engine_isValid;

    m_client_engine_version_isValid = ::OpenAPI::fromJsonValue(client_engine_version, json[QString("clientEngineVersion")]);
    m_client_engine_version_isSet = !json[QString("clientEngineVersion")].isNull() && m_client_engine_version_isValid;

    m_device_name_isValid = ::OpenAPI::fromJsonValue(device_name, json[QString("deviceName")]);
    m_device_name_isSet = !json[QString("deviceName")].isNull() && m_device_name_isValid;

    m_device_brand_isValid = ::OpenAPI::fromJsonValue(device_brand, json[QString("deviceBrand")]);
    m_device_brand_isSet = !json[QString("deviceBrand")].isNull() && m_device_brand_isValid;

    m_device_model_isValid = ::OpenAPI::fromJsonValue(device_model, json[QString("deviceModel")]);
    m_device_model_isSet = !json[QString("deviceModel")].isNull() && m_device_model_isValid;

    m_country_code_isValid = ::OpenAPI::fromJsonValue(country_code, json[QString("countryCode")]);
    m_country_code_isSet = !json[QString("countryCode")].isNull() && m_country_code_isValid;

    m_country_name_isValid = ::OpenAPI::fromJsonValue(country_name, json[QString("countryName")]);
    m_country_name_isSet = !json[QString("countryName")].isNull() && m_country_name_isValid;
}

QString AWLog::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWLog::asJsonObject() const {
    QJsonObject obj;
    if (m_event_isSet) {
        obj.insert(QString("event"), ::OpenAPI::toJsonValue(event));
    }
    if (m_user_id_isSet) {
        obj.insert(QString("userId"), ::OpenAPI::toJsonValue(user_id));
    }
    if (m_user_email_isSet) {
        obj.insert(QString("userEmail"), ::OpenAPI::toJsonValue(user_email));
    }
    if (m_user_name_isSet) {
        obj.insert(QString("userName"), ::OpenAPI::toJsonValue(user_name));
    }
    if (m_mode_isSet) {
        obj.insert(QString("mode"), ::OpenAPI::toJsonValue(mode));
    }
    if (m_ip_isSet) {
        obj.insert(QString("ip"), ::OpenAPI::toJsonValue(ip));
    }
    if (m_time_isSet) {
        obj.insert(QString("time"), ::OpenAPI::toJsonValue(time));
    }
    if (m_os_code_isSet) {
        obj.insert(QString("osCode"), ::OpenAPI::toJsonValue(os_code));
    }
    if (m_os_name_isSet) {
        obj.insert(QString("osName"), ::OpenAPI::toJsonValue(os_name));
    }
    if (m_os_version_isSet) {
        obj.insert(QString("osVersion"), ::OpenAPI::toJsonValue(os_version));
    }
    if (m_client_type_isSet) {
        obj.insert(QString("clientType"), ::OpenAPI::toJsonValue(client_type));
    }
    if (m_client_code_isSet) {
        obj.insert(QString("clientCode"), ::OpenAPI::toJsonValue(client_code));
    }
    if (m_client_name_isSet) {
        obj.insert(QString("clientName"), ::OpenAPI::toJsonValue(client_name));
    }
    if (m_client_version_isSet) {
        obj.insert(QString("clientVersion"), ::OpenAPI::toJsonValue(client_version));
    }
    if (m_client_engine_isSet) {
        obj.insert(QString("clientEngine"), ::OpenAPI::toJsonValue(client_engine));
    }
    if (m_client_engine_version_isSet) {
        obj.insert(QString("clientEngineVersion"), ::OpenAPI::toJsonValue(client_engine_version));
    }
    if (m_device_name_isSet) {
        obj.insert(QString("deviceName"), ::OpenAPI::toJsonValue(device_name));
    }
    if (m_device_brand_isSet) {
        obj.insert(QString("deviceBrand"), ::OpenAPI::toJsonValue(device_brand));
    }
    if (m_device_model_isSet) {
        obj.insert(QString("deviceModel"), ::OpenAPI::toJsonValue(device_model));
    }
    if (m_country_code_isSet) {
        obj.insert(QString("countryCode"), ::OpenAPI::toJsonValue(country_code));
    }
    if (m_country_name_isSet) {
        obj.insert(QString("countryName"), ::OpenAPI::toJsonValue(country_name));
    }
    return obj;
}

QString AWLog::getEvent() const {
    return event;
}
void AWLog::setEvent(const QString &event) {
    this->event = event;
    this->m_event_isSet = true;
}

bool AWLog::is_event_Set() const{
    return m_event_isSet;
}

bool AWLog::is_event_Valid() const{
    return m_event_isValid;
}

QString AWLog::getUserId() const {
    return user_id;
}
void AWLog::setUserId(const QString &user_id) {
    this->user_id = user_id;
    this->m_user_id_isSet = true;
}

bool AWLog::is_user_id_Set() const{
    return m_user_id_isSet;
}

bool AWLog::is_user_id_Valid() const{
    return m_user_id_isValid;
}

QString AWLog::getUserEmail() const {
    return user_email;
}
void AWLog::setUserEmail(const QString &user_email) {
    this->user_email = user_email;
    this->m_user_email_isSet = true;
}

bool AWLog::is_user_email_Set() const{
    return m_user_email_isSet;
}

bool AWLog::is_user_email_Valid() const{
    return m_user_email_isValid;
}

QString AWLog::getUserName() const {
    return user_name;
}
void AWLog::setUserName(const QString &user_name) {
    this->user_name = user_name;
    this->m_user_name_isSet = true;
}

bool AWLog::is_user_name_Set() const{
    return m_user_name_isSet;
}

bool AWLog::is_user_name_Valid() const{
    return m_user_name_isValid;
}

QString AWLog::getMode() const {
    return mode;
}
void AWLog::setMode(const QString &mode) {
    this->mode = mode;
    this->m_mode_isSet = true;
}

bool AWLog::is_mode_Set() const{
    return m_mode_isSet;
}

bool AWLog::is_mode_Valid() const{
    return m_mode_isValid;
}

QString AWLog::getIp() const {
    return ip;
}
void AWLog::setIp(const QString &ip) {
    this->ip = ip;
    this->m_ip_isSet = true;
}

bool AWLog::is_ip_Set() const{
    return m_ip_isSet;
}

bool AWLog::is_ip_Valid() const{
    return m_ip_isValid;
}

QString AWLog::getTime() const {
    return time;
}
void AWLog::setTime(const QString &time) {
    this->time = time;
    this->m_time_isSet = true;
}

bool AWLog::is_time_Set() const{
    return m_time_isSet;
}

bool AWLog::is_time_Valid() const{
    return m_time_isValid;
}

QString AWLog::getOsCode() const {
    return os_code;
}
void AWLog::setOsCode(const QString &os_code) {
    this->os_code = os_code;
    this->m_os_code_isSet = true;
}

bool AWLog::is_os_code_Set() const{
    return m_os_code_isSet;
}

bool AWLog::is_os_code_Valid() const{
    return m_os_code_isValid;
}

QString AWLog::getOsName() const {
    return os_name;
}
void AWLog::setOsName(const QString &os_name) {
    this->os_name = os_name;
    this->m_os_name_isSet = true;
}

bool AWLog::is_os_name_Set() const{
    return m_os_name_isSet;
}

bool AWLog::is_os_name_Valid() const{
    return m_os_name_isValid;
}

QString AWLog::getOsVersion() const {
    return os_version;
}
void AWLog::setOsVersion(const QString &os_version) {
    this->os_version = os_version;
    this->m_os_version_isSet = true;
}

bool AWLog::is_os_version_Set() const{
    return m_os_version_isSet;
}

bool AWLog::is_os_version_Valid() const{
    return m_os_version_isValid;
}

QString AWLog::getClientType() const {
    return client_type;
}
void AWLog::setClientType(const QString &client_type) {
    this->client_type = client_type;
    this->m_client_type_isSet = true;
}

bool AWLog::is_client_type_Set() const{
    return m_client_type_isSet;
}

bool AWLog::is_client_type_Valid() const{
    return m_client_type_isValid;
}

QString AWLog::getClientCode() const {
    return client_code;
}
void AWLog::setClientCode(const QString &client_code) {
    this->client_code = client_code;
    this->m_client_code_isSet = true;
}

bool AWLog::is_client_code_Set() const{
    return m_client_code_isSet;
}

bool AWLog::is_client_code_Valid() const{
    return m_client_code_isValid;
}

QString AWLog::getClientName() const {
    return client_name;
}
void AWLog::setClientName(const QString &client_name) {
    this->client_name = client_name;
    this->m_client_name_isSet = true;
}

bool AWLog::is_client_name_Set() const{
    return m_client_name_isSet;
}

bool AWLog::is_client_name_Valid() const{
    return m_client_name_isValid;
}

QString AWLog::getClientVersion() const {
    return client_version;
}
void AWLog::setClientVersion(const QString &client_version) {
    this->client_version = client_version;
    this->m_client_version_isSet = true;
}

bool AWLog::is_client_version_Set() const{
    return m_client_version_isSet;
}

bool AWLog::is_client_version_Valid() const{
    return m_client_version_isValid;
}

QString AWLog::getClientEngine() const {
    return client_engine;
}
void AWLog::setClientEngine(const QString &client_engine) {
    this->client_engine = client_engine;
    this->m_client_engine_isSet = true;
}

bool AWLog::is_client_engine_Set() const{
    return m_client_engine_isSet;
}

bool AWLog::is_client_engine_Valid() const{
    return m_client_engine_isValid;
}

QString AWLog::getClientEngineVersion() const {
    return client_engine_version;
}
void AWLog::setClientEngineVersion(const QString &client_engine_version) {
    this->client_engine_version = client_engine_version;
    this->m_client_engine_version_isSet = true;
}

bool AWLog::is_client_engine_version_Set() const{
    return m_client_engine_version_isSet;
}

bool AWLog::is_client_engine_version_Valid() const{
    return m_client_engine_version_isValid;
}

QString AWLog::getDeviceName() const {
    return device_name;
}
void AWLog::setDeviceName(const QString &device_name) {
    this->device_name = device_name;
    this->m_device_name_isSet = true;
}

bool AWLog::is_device_name_Set() const{
    return m_device_name_isSet;
}

bool AWLog::is_device_name_Valid() const{
    return m_device_name_isValid;
}

QString AWLog::getDeviceBrand() const {
    return device_brand;
}
void AWLog::setDeviceBrand(const QString &device_brand) {
    this->device_brand = device_brand;
    this->m_device_brand_isSet = true;
}

bool AWLog::is_device_brand_Set() const{
    return m_device_brand_isSet;
}

bool AWLog::is_device_brand_Valid() const{
    return m_device_brand_isValid;
}

QString AWLog::getDeviceModel() const {
    return device_model;
}
void AWLog::setDeviceModel(const QString &device_model) {
    this->device_model = device_model;
    this->m_device_model_isSet = true;
}

bool AWLog::is_device_model_Set() const{
    return m_device_model_isSet;
}

bool AWLog::is_device_model_Valid() const{
    return m_device_model_isValid;
}

QString AWLog::getCountryCode() const {
    return country_code;
}
void AWLog::setCountryCode(const QString &country_code) {
    this->country_code = country_code;
    this->m_country_code_isSet = true;
}

bool AWLog::is_country_code_Set() const{
    return m_country_code_isSet;
}

bool AWLog::is_country_code_Valid() const{
    return m_country_code_isValid;
}

QString AWLog::getCountryName() const {
    return country_name;
}
void AWLog::setCountryName(const QString &country_name) {
    this->country_name = country_name;
    this->m_country_name_isSet = true;
}

bool AWLog::is_country_name_Set() const{
    return m_country_name_isSet;
}

bool AWLog::is_country_name_Valid() const{
    return m_country_name_isValid;
}

bool AWLog::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_event_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_email_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_mode_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_ip_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_time_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_os_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_os_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_os_version_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_client_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_client_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_client_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_client_version_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_client_engine_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_client_engine_version_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_device_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_device_brand_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_device_model_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_country_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_country_name_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWLog::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_event_isValid && m_user_id_isValid && m_user_email_isValid && m_user_name_isValid && m_mode_isValid && m_ip_isValid && m_time_isValid && m_os_code_isValid && m_os_name_isValid && m_os_version_isValid && m_client_type_isValid && m_client_code_isValid && m_client_name_isValid && m_client_version_isValid && m_client_engine_isValid && m_client_engine_version_isValid && m_device_name_isValid && m_device_brand_isValid && m_device_model_isValid && m_country_code_isValid && m_country_name_isValid && true;
}

} // namespace OpenAPI
