/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AWMembership.h
 *
 * Membership
 */

#ifndef AWMEMBERSHIP_H
#define AWMEMBERSHIP_H

#include <QJsonObject>

#include <QList>
#include <QString>

#include "src/AWEnum.h"
#include "src/AWObject.h"

#include "src/AWGlobalExport.h"

namespace OpenAPI {

class APPWRITE_EXPORT AWMembership : public AWObject {
public:
    AWMembership();
    AWMembership(QString json);
    ~AWMembership() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getCreatedAt() const;
    void setCreatedAt(const QString &created_at);
    bool is_created_at_Set() const;
    bool is_created_at_Valid() const;

    QString getUpdatedAt() const;
    void setUpdatedAt(const QString &updated_at);
    bool is_updated_at_Set() const;
    bool is_updated_at_Valid() const;

    QString getUserId() const;
    void setUserId(const QString &user_id);
    bool is_user_id_Set() const;
    bool is_user_id_Valid() const;

    QString getUserName() const;
    void setUserName(const QString &user_name);
    bool is_user_name_Set() const;
    bool is_user_name_Valid() const;

    QString getUserEmail() const;
    void setUserEmail(const QString &user_email);
    bool is_user_email_Set() const;
    bool is_user_email_Valid() const;

    QString getTeamId() const;
    void setTeamId(const QString &team_id);
    bool is_team_id_Set() const;
    bool is_team_id_Valid() const;

    QString getTeamName() const;
    void setTeamName(const QString &team_name);
    bool is_team_name_Set() const;
    bool is_team_name_Valid() const;

    QString getInvited() const;
    void setInvited(const QString &invited);
    bool is_invited_Set() const;
    bool is_invited_Valid() const;

    QString getJoined() const;
    void setJoined(const QString &joined);
    bool is_joined_Set() const;
    bool is_joined_Valid() const;

    bool isConfirm() const;
    void setConfirm(const bool &confirm);
    bool is_confirm_Set() const;
    bool is_confirm_Valid() const;

    QList<QString> getRoles() const;
    void setRoles(const QList<QString> &roles);
    bool is_roles_Set() const;
    bool is_roles_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString created_at;
    bool m_created_at_isSet;
    bool m_created_at_isValid;

    QString updated_at;
    bool m_updated_at_isSet;
    bool m_updated_at_isValid;

    QString user_id;
    bool m_user_id_isSet;
    bool m_user_id_isValid;

    QString user_name;
    bool m_user_name_isSet;
    bool m_user_name_isValid;

    QString user_email;
    bool m_user_email_isSet;
    bool m_user_email_isValid;

    QString team_id;
    bool m_team_id_isSet;
    bool m_team_id_isValid;

    QString team_name;
    bool m_team_name_isSet;
    bool m_team_name_isValid;

    QString invited;
    bool m_invited_isSet;
    bool m_invited_isValid;

    QString joined;
    bool m_joined_isSet;
    bool m_joined_isValid;

    bool confirm;
    bool m_confirm_isSet;
    bool m_confirm_isValid;

    QList<QString> roles;
    bool m_roles_isSet;
    bool m_roles_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::AWMembership)

#endif // AWMEMBERSHIP_H
