/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AWMembershipList.h
 *
 * Memberships List
 */

#ifndef AWMEMBERSHIPLIST_H
#define AWMEMBERSHIPLIST_H

#include <QJsonObject>

#include "src/model/AWMembership.h"
#include <QList>

#include "src/AWEnum.h"
#include "src/AWObject.h"

#include "src/AWGlobalExport.h"

namespace OpenAPI {
class AWMembership;

class APPWRITE_EXPORT AWMembershipList : public AWObject {
public:
    AWMembershipList();
    AWMembershipList(QString json);
    ~AWMembershipList() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getTotal() const;
    void setTotal(const qint32 &total);
    bool is_total_Set() const;
    bool is_total_Valid() const;

    QList<AWMembership> getMemberships() const;
    void setMemberships(const QList<AWMembership> &memberships);
    bool is_memberships_Set() const;
    bool is_memberships_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 total;
    bool m_total_isSet;
    bool m_total_isValid;

    QList<AWMembership> memberships;
    bool m_memberships_isSet;
    bool m_memberships_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::AWMembershipList)

#endif // AWMEMBERSHIPLIST_H
