/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "AWPhoneList.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "src/AWHelpers.h"

namespace OpenAPI {

AWPhoneList::AWPhoneList(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

AWPhoneList::AWPhoneList() {
    this->initializeModel();
}

AWPhoneList::~AWPhoneList() {}

void AWPhoneList::initializeModel() {

    m_total_isSet = false;
    m_total_isValid = false;

    m_phones_isSet = false;
    m_phones_isValid = false;
}

void AWPhoneList::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void AWPhoneList::fromJsonObject(QJsonObject json) {

    m_total_isValid = ::OpenAPI::fromJsonValue(total, json[QString("total")]);
    m_total_isSet = !json[QString("total")].isNull() && m_total_isValid;

    m_phones_isValid = ::OpenAPI::fromJsonValue(phones, json[QString("phones")]);
    m_phones_isSet = !json[QString("phones")].isNull() && m_phones_isValid;
}

QString AWPhoneList::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject AWPhoneList::asJsonObject() const {
    QJsonObject obj;
    if (m_total_isSet) {
        obj.insert(QString("total"), ::OpenAPI::toJsonValue(total));
    }
    if (phones.size() > 0) {
        obj.insert(QString("phones"), ::OpenAPI::toJsonValue(phones));
    }
    return obj;
}

qint32 AWPhoneList::getTotal() const {
    return total;
}
void AWPhoneList::setTotal(const qint32 &total) {
    this->total = total;
    this->m_total_isSet = true;
}

bool AWPhoneList::is_total_Set() const{
    return m_total_isSet;
}

bool AWPhoneList::is_total_Valid() const{
    return m_total_isValid;
}

QList<AWPhone> AWPhoneList::getPhones() const {
    return phones;
}
void AWPhoneList::setPhones(const QList<AWPhone> &phones) {
    this->phones = phones;
    this->m_phones_isSet = true;
}

bool AWPhoneList::is_phones_Set() const{
    return m_phones_isSet;
}

bool AWPhoneList::is_phones_Valid() const{
    return m_phones_isValid;
}

bool AWPhoneList::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_total_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (phones.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool AWPhoneList::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_total_isValid && m_phones_isValid && true;
}

} // namespace OpenAPI
