/**
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AWSession.h
 *
 * Session
 */

#ifndef AWSESSION_H
#define AWSESSION_H

#include <QJsonObject>

#include <QString>

#include "src/AWEnum.h"
#include "src/AWObject.h"

#include "src/AWGlobalExport.h"

namespace OpenAPI {

class APPWRITE_EXPORT AWSession : public AWObject {
public:
    AWSession();
    AWSession(QString json);
    ~AWSession() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getCreatedAt() const;
    void setCreatedAt(const QString &created_at);
    bool is_created_at_Set() const;
    bool is_created_at_Valid() const;

    QString getUserId() const;
    void setUserId(const QString &user_id);
    bool is_user_id_Set() const;
    bool is_user_id_Valid() const;

    QString getExpire() const;
    void setExpire(const QString &expire);
    bool is_expire_Set() const;
    bool is_expire_Valid() const;

    QString getProvider() const;
    void setProvider(const QString &provider);
    bool is_provider_Set() const;
    bool is_provider_Valid() const;

    QString getProviderUid() const;
    void setProviderUid(const QString &provider_uid);
    bool is_provider_uid_Set() const;
    bool is_provider_uid_Valid() const;

    QString getProviderAccessToken() const;
    void setProviderAccessToken(const QString &provider_access_token);
    bool is_provider_access_token_Set() const;
    bool is_provider_access_token_Valid() const;

    QString getProviderAccessTokenExpiry() const;
    void setProviderAccessTokenExpiry(const QString &provider_access_token_expiry);
    bool is_provider_access_token_expiry_Set() const;
    bool is_provider_access_token_expiry_Valid() const;

    QString getProviderRefreshToken() const;
    void setProviderRefreshToken(const QString &provider_refresh_token);
    bool is_provider_refresh_token_Set() const;
    bool is_provider_refresh_token_Valid() const;

    QString getIp() const;
    void setIp(const QString &ip);
    bool is_ip_Set() const;
    bool is_ip_Valid() const;

    QString getOsCode() const;
    void setOsCode(const QString &os_code);
    bool is_os_code_Set() const;
    bool is_os_code_Valid() const;

    QString getOsName() const;
    void setOsName(const QString &os_name);
    bool is_os_name_Set() const;
    bool is_os_name_Valid() const;

    QString getOsVersion() const;
    void setOsVersion(const QString &os_version);
    bool is_os_version_Set() const;
    bool is_os_version_Valid() const;

    QString getClientType() const;
    void setClientType(const QString &client_type);
    bool is_client_type_Set() const;
    bool is_client_type_Valid() const;

    QString getClientCode() const;
    void setClientCode(const QString &client_code);
    bool is_client_code_Set() const;
    bool is_client_code_Valid() const;

    QString getClientName() const;
    void setClientName(const QString &client_name);
    bool is_client_name_Set() const;
    bool is_client_name_Valid() const;

    QString getClientVersion() const;
    void setClientVersion(const QString &client_version);
    bool is_client_version_Set() const;
    bool is_client_version_Valid() const;

    QString getClientEngine() const;
    void setClientEngine(const QString &client_engine);
    bool is_client_engine_Set() const;
    bool is_client_engine_Valid() const;

    QString getClientEngineVersion() const;
    void setClientEngineVersion(const QString &client_engine_version);
    bool is_client_engine_version_Set() const;
    bool is_client_engine_version_Valid() const;

    QString getDeviceName() const;
    void setDeviceName(const QString &device_name);
    bool is_device_name_Set() const;
    bool is_device_name_Valid() const;

    QString getDeviceBrand() const;
    void setDeviceBrand(const QString &device_brand);
    bool is_device_brand_Set() const;
    bool is_device_brand_Valid() const;

    QString getDeviceModel() const;
    void setDeviceModel(const QString &device_model);
    bool is_device_model_Set() const;
    bool is_device_model_Valid() const;

    QString getCountryCode() const;
    void setCountryCode(const QString &country_code);
    bool is_country_code_Set() const;
    bool is_country_code_Valid() const;

    QString getCountryName() const;
    void setCountryName(const QString &country_name);
    bool is_country_name_Set() const;
    bool is_country_name_Valid() const;

    bool isCurrent() const;
    void setCurrent(const bool &current);
    bool is_current_Set() const;
    bool is_current_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString created_at;
    bool m_created_at_isSet;
    bool m_created_at_isValid;

    QString user_id;
    bool m_user_id_isSet;
    bool m_user_id_isValid;

    QString expire;
    bool m_expire_isSet;
    bool m_expire_isValid;

    QString provider;
    bool m_provider_isSet;
    bool m_provider_isValid;

    QString provider_uid;
    bool m_provider_uid_isSet;
    bool m_provider_uid_isValid;

    QString provider_access_token;
    bool m_provider_access_token_isSet;
    bool m_provider_access_token_isValid;

    QString provider_access_token_expiry;
    bool m_provider_access_token_expiry_isSet;
    bool m_provider_access_token_expiry_isValid;

    QString provider_refresh_token;
    bool m_provider_refresh_token_isSet;
    bool m_provider_refresh_token_isValid;

    QString ip;
    bool m_ip_isSet;
    bool m_ip_isValid;

    QString os_code;
    bool m_os_code_isSet;
    bool m_os_code_isValid;

    QString os_name;
    bool m_os_name_isSet;
    bool m_os_name_isValid;

    QString os_version;
    bool m_os_version_isSet;
    bool m_os_version_isValid;

    QString client_type;
    bool m_client_type_isSet;
    bool m_client_type_isValid;

    QString client_code;
    bool m_client_code_isSet;
    bool m_client_code_isValid;

    QString client_name;
    bool m_client_name_isSet;
    bool m_client_name_isValid;

    QString client_version;
    bool m_client_version_isSet;
    bool m_client_version_isValid;

    QString client_engine;
    bool m_client_engine_isSet;
    bool m_client_engine_isValid;

    QString client_engine_version;
    bool m_client_engine_version_isSet;
    bool m_client_engine_version_isValid;

    QString device_name;
    bool m_device_name_isSet;
    bool m_device_name_isValid;

    QString device_brand;
    bool m_device_brand_isSet;
    bool m_device_brand_isValid;

    QString device_model;
    bool m_device_model_isSet;
    bool m_device_model_isValid;

    QString country_code;
    bool m_country_code_isSet;
    bool m_country_code_isValid;

    QString country_name;
    bool m_country_name_isSet;
    bool m_country_name_isValid;

    bool current;
    bool m_current_isSet;
    bool m_current_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::AWSession)

#endif // AWSESSION_H
