QT += network

HEADERS += \
# Models
    $${PWD}/model/AWAccountCreateEmailSessionRequest.h \
    $${PWD}/model/AWAccountCreateMagicURLSessionRequest.h \
    $${PWD}/model/AWAccountCreatePhoneSessionRequest.h \
    $${PWD}/model/AWAccountCreateRecoveryRequest.h \
    $${PWD}/model/AWAccountCreateRequest.h \
    $${PWD}/model/AWAccountCreateVerificationRequest.h \
    $${PWD}/model/AWAccountUpdateEmailRequest.h \
    $${PWD}/model/AWAccountUpdateMagicURLSessionRequest.h \
    $${PWD}/model/AWAccountUpdateNameRequest.h \
    $${PWD}/model/AWAccountUpdatePasswordRequest.h \
    $${PWD}/model/AWAccountUpdatePhoneRequest.h \
    $${PWD}/model/AWAccountUpdatePhoneSessionRequest.h \
    $${PWD}/model/AWAccountUpdatePhoneVerificationRequest.h \
    $${PWD}/model/AWAccountUpdatePrefsRequest.h \
    $${PWD}/model/AWAccountUpdateRecoveryRequest.h \
    $${PWD}/model/AWAccountUpdateVerificationRequest.h \
    $${PWD}/model/AWAlgoArgon2.h \
    $${PWD}/model/AWAlgoBcrypt.h \
    $${PWD}/model/AWAlgoMd5.h \
    $${PWD}/model/AWAlgoPhpass.h \
    $${PWD}/model/AWAlgoScrypt.h \
    $${PWD}/model/AWAlgoScryptModified.h \
    $${PWD}/model/AWAlgoSha.h \
    $${PWD}/model/AWContinent.h \
    $${PWD}/model/AWContinentList.h \
    $${PWD}/model/AWCountry.h \
    $${PWD}/model/AWCountryList.h \
    $${PWD}/model/AWCurrency.h \
    $${PWD}/model/AWCurrencyList.h \
    $${PWD}/model/AWDatabasesCreateDocumentRequest.h \
    $${PWD}/model/AWDatabasesUpdateDocumentRequest.h \
    $${PWD}/model/AWDocument.h \
    $${PWD}/model/AWDocumentList.h \
    $${PWD}/model/AWError.h \
    $${PWD}/model/AWExecution.h \
    $${PWD}/model/AWExecutionList.h \
    $${PWD}/model/AWFileEx.h \
    $${PWD}/model/AWFileList.h \
    $${PWD}/model/AWFunctionsCreateExecutionRequest.h \
    $${PWD}/model/AWJwt.h \
    $${PWD}/model/AWLanguage.h \
    $${PWD}/model/AWLanguageList.h \
    $${PWD}/model/AWLocale.h \
    $${PWD}/model/AWLog.h \
    $${PWD}/model/AWLogList.h \
    $${PWD}/model/AWMembership.h \
    $${PWD}/model/AWMembershipList.h \
    $${PWD}/model/AWPhone.h \
    $${PWD}/model/AWPhoneList.h \
    $${PWD}/model/AWSession.h \
    $${PWD}/model/AWSessionList.h \
    $${PWD}/model/AWStorageUpdateFileRequest.h \
    $${PWD}/model/AWTeam.h \
    $${PWD}/model/AWTeamList.h \
    $${PWD}/model/AWTeamsCreateMembershipRequest.h \
    $${PWD}/model/AWTeamsCreateRequest.h \
    $${PWD}/model/AWTeamsUpdateMembershipRolesRequest.h \
    $${PWD}/model/AWTeamsUpdateMembershipStatusRequest.h \
    $${PWD}/model/AWTeamsUpdateNameRequest.h \
    $${PWD}/model/AWTeamsUpdatePrefsRequest.h \
    $${PWD}/model/AWToken.h \
    $${PWD}/model/AWUser.h \
    $${PWD}/model/AWUserHashOptionsInner_inner.h \
# APIs
    $${PWD}/api/AWAccountApi.h \
    $${PWD}/api/AWAvatarsApi.h \
    $${PWD}/api/AWDatabasesApi.h \
    $${PWD}/api/AWFunctionsApi.h \
    $${PWD}/api/AWGraphqlApi.h \
    $${PWD}/api/AWLocaleApi.h \
    $${PWD}/api/AWStorageApi.h \
    $${PWD}/api/AWTeamsApi.h \
# Others
    $${PWD}/AWHelpers.h \
    $${PWD}/AWHttpRequest.h \
    $${PWD}/AWObject.h \
    $${PWD}/AWEnum.h \
    $${PWD}/AWGlobalExport.h \
    $${PWD}/AWHttpFileElement.h \
    $${PWD}/AWServerConfiguration.h \
    $${PWD}/AWServerVariable.h \
    $${PWD}/AWOauth.h

SOURCES += \
# Models
    $${PWD}/model/AWAccountCreateEmailSessionRequest.cpp \
    $${PWD}/model/AWAccountCreateMagicURLSessionRequest.cpp \
    $${PWD}/model/AWAccountCreatePhoneSessionRequest.cpp \
    $${PWD}/model/AWAccountCreateRecoveryRequest.cpp \
    $${PWD}/model/AWAccountCreateRequest.cpp \
    $${PWD}/model/AWAccountCreateVerificationRequest.cpp \
    $${PWD}/model/AWAccountUpdateEmailRequest.cpp \
    $${PWD}/model/AWAccountUpdateMagicURLSessionRequest.cpp \
    $${PWD}/model/AWAccountUpdateNameRequest.cpp \
    $${PWD}/model/AWAccountUpdatePasswordRequest.cpp \
    $${PWD}/model/AWAccountUpdatePhoneRequest.cpp \
    $${PWD}/model/AWAccountUpdatePhoneSessionRequest.cpp \
    $${PWD}/model/AWAccountUpdatePhoneVerificationRequest.cpp \
    $${PWD}/model/AWAccountUpdatePrefsRequest.cpp \
    $${PWD}/model/AWAccountUpdateRecoveryRequest.cpp \
    $${PWD}/model/AWAccountUpdateVerificationRequest.cpp \
    $${PWD}/model/AWAlgoArgon2.cpp \
    $${PWD}/model/AWAlgoBcrypt.cpp \
    $${PWD}/model/AWAlgoMd5.cpp \
    $${PWD}/model/AWAlgoPhpass.cpp \
    $${PWD}/model/AWAlgoScrypt.cpp \
    $${PWD}/model/AWAlgoScryptModified.cpp \
    $${PWD}/model/AWAlgoSha.cpp \
    $${PWD}/model/AWContinent.cpp \
    $${PWD}/model/AWContinentList.cpp \
    $${PWD}/model/AWCountry.cpp \
    $${PWD}/model/AWCountryList.cpp \
    $${PWD}/model/AWCurrency.cpp \
    $${PWD}/model/AWCurrencyList.cpp \
    $${PWD}/model/AWDatabasesCreateDocumentRequest.cpp \
    $${PWD}/model/AWDatabasesUpdateDocumentRequest.cpp \
    $${PWD}/model/AWDocument.cpp \
    $${PWD}/model/AWDocumentList.cpp \
    $${PWD}/model/AWError.cpp \
    $${PWD}/model/AWExecution.cpp \
    $${PWD}/model/AWExecutionList.cpp \
    $${PWD}/model/AWFileEx.cpp \
    $${PWD}/model/AWFileList.cpp \
    $${PWD}/model/AWFunctionsCreateExecutionRequest.cpp \
    $${PWD}/model/AWJwt.cpp \
    $${PWD}/model/AWLanguage.cpp \
    $${PWD}/model/AWLanguageList.cpp \
    $${PWD}/model/AWLocale.cpp \
    $${PWD}/model/AWLog.cpp \
    $${PWD}/model/AWLogList.cpp \
    $${PWD}/model/AWMembership.cpp \
    $${PWD}/model/AWMembershipList.cpp \
    $${PWD}/model/AWPhone.cpp \
    $${PWD}/model/AWPhoneList.cpp \
    $${PWD}/model/AWSession.cpp \
    $${PWD}/model/AWSessionList.cpp \
    $${PWD}/model/AWStorageUpdateFileRequest.cpp \
    $${PWD}/model/AWTeam.cpp \
    $${PWD}/model/AWTeamList.cpp \
    $${PWD}/model/AWTeamsCreateMembershipRequest.cpp \
    $${PWD}/model/AWTeamsCreateRequest.cpp \
    $${PWD}/model/AWTeamsUpdateMembershipRolesRequest.cpp \
    $${PWD}/model/AWTeamsUpdateMembershipStatusRequest.cpp \
    $${PWD}/model/AWTeamsUpdateNameRequest.cpp \
    $${PWD}/model/AWTeamsUpdatePrefsRequest.cpp \
    $${PWD}/model/AWToken.cpp \
    $${PWD}/model/AWUser.cpp \
    $${PWD}/model/AWUserHashOptionsInner_inner.cpp \
# APIs
    $${PWD}/api/AWAccountApi.cpp \
    $${PWD}/api/AWAvatarsApi.cpp \
    $${PWD}/api/AWDatabasesApi.cpp \
    $${PWD}/api/AWFunctionsApi.cpp \
    $${PWD}/api/AWGraphqlApi.cpp \
    $${PWD}/api/AWLocaleApi.cpp \
    $${PWD}/api/AWStorageApi.cpp \
    $${PWD}/api/AWTeamsApi.cpp \
# Others
    $${PWD}/AWHelpers.cpp \
    $${PWD}/AWHttpRequest.cpp \
    $${PWD}/AWHttpFileElement.cpp \
    $${PWD}/AWOauth.cpp
